packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@embedded-postgres/windows-x64': true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - embedded-postgres
  - unrs-resolver
  - "@embedded-postgres/windows-x64"
